name: Allure Report
run-name: ${{ github.actor }} is creating Allure report 🚀

on:
  push:
    branches-ignore:
      - '!main'

permissions: write-all

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest

    steps:

      - name: "Install project's dependencies"
        run: |
          corepack enable
          yarn set version stable
          yarn config set -H enableImmutableInstalls false
          yarn install

      - name: Clone repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node 20
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20
          cache: yarn


      - name: Install yarn
        run: yarn install

      - run: yarn test
        continue-on-error: true

      - name: Prepare Allure Results Directory
        run: |
          mkdir -p ./out/allure-results/history
          mkdir -p allure-history/last-history

      - name: Setup Allure History
        uses: actions/checkout@v4.1.7
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages


      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
