name: Allure Report
run-name: ${{ github.actor }} is creating Allure report 🚀

on:
  push:
    branches-ignore:
      - '!main'

permissions: write-all

jobs:
  autotests:
    name: Run tests and generate Allure Report 
    runs-on: ubuntu-latest

    steps:
      - name: "Set pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: 8


      - name: Clone repository
        uses: actions/checkout@v4.2.0

      - name: Set up Node 
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 
          cache: pnpm


      - name: Install pnpm
        run: pnpm install

      - run: pnpm test
        continue-on-error: true

      - name: Setup Allure History
        uses: actions/checkout@v4.2.0
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
