name: config-codeceptjs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/config-codeceptjs/**"
      - ".github/workflows/verify-codeceptjs.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/config-codeceptjs/**"
      - ".github/workflows/verify-codeceptjs.yaml"

env:
  ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: "Install dependencies"
        run: |
          yarn install --immutable --immutable-cache
      - name: "Build workspace packages"
        run: |
          yarn build
      - name: "pack @allure-start/cli"
        run: |
          yarn workspace @allure-start/cli pack
      - name: "Create @allure-start/cli artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "allure-start-cli"
          path: |
            ./packages/cli/package.tgz

  generate-codeceptjs:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        builder: ["npm", "yarn", "pnpm"]
        lang: ["js", "ts"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install pnpm
        if: matrix.builder == 'pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: "Download artifact"
        uses: actions/download-artifact@v3
        with:
          name: "allure-start-cli"
      - name: "Unpack allure start"
        run: |
          tar -xvzf package.tgz
      - name: "$ allure-start --help"
        run: |
          node package/bin/start --help
      - name: "Generate project"
        run: >
          node package/bin/start write 
          --id codeceptjs 
          --builder ${{ matrix.builder }} 
          --lang ${{ matrix.lang }}
          --name "codeceptjs-${{ matrix.lang }}-${{ matrix.builder }}"
          ./out
      - name: "Create project's artifact"
        uses: actions/upload-artifact@v3
        with:
          name: codeceptjs-${{ matrix.lang }}-${{ matrix.builder }}
          path: |
            ./out

  verify-codeceptjs:
    needs: generate-codeceptjs
    strategy:
      fail-fast: false
      matrix:
        builder: ["npm", "yarn", "pnpm"]
        lang: ["js", "ts"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install pnpm
        if: matrix.builder == 'pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: "Download artifact"
        uses: actions/download-artifact@v3
        with:
          name: codeceptjs-${{ matrix.lang }}-${{ matrix.builder }}
      - name: "Install project's dependencies"
        if: matrix.builder == 'npm'
        run: |
          npm install
      - name: "Run project's tests"
        if: matrix.builder == 'npm'
        run: |
          npm run test
      - name: "Install project's dependencies"
        if: matrix.builder == 'yarn'
        run: |
          corepack enable
          yarn set version stable
          yarn config set -H enableImmutableInstalls false
          yarn install
      - name: "Run project's tests"
        if: matrix.builder == 'yarn'
        run: |
          yarn test
      - name: "Install project's dependencies"
        if: matrix.builder == 'pnpm'
        run: |
          pnpm install
      - name: "Run project's tests"
        if: matrix.builder == 'pnpm'
        run: |
          pnpm test
